
[functions.embed-search]
enabled = true
verify_jwt = true
entrypoint = "./functions/embed-search/index.ts"

[functions.send_push_notification]
enabled = true
verify_jwt = true
import_map = "./functions/send_push_notification/deno.json"
entrypoint = "./functions/send_push_notification/index.ts"

[functions.broadcast_push]
enabled = true
verify_jwt = false
import_map = "./functions/broadcast_push/deno.json"
entrypoint = "./functions/broadcast_push/index.ts"

[functions.crawl_hkbu]
enabled = true
verify_jwt = false
entrypoint = "./functions/crawl_hkbu/index.ts"
